fix #1 メンションテスト用Issue
SlackMentionTestOrg/slack-mention-test pull request #2
Opened 2021-09-01 05:09 UTC by KazukiMorisawa

#1 

他に修正したリポジトリはありません。

2021-09-01 05:11 UTC, osaku-junichiro commented
@KazukiMorisawa cc @osaku-junichiro  作成ありがとうございます。workflowのテストです。

2021-09-01 05:36 UTC, osaku-junichiro commented
@KazukiMorisawa cc @osaku-junichiro コミット追加後のworkflowのテストです。

2021-09-01 05:54 UTC, osaku-junichiro requested changes
@KazukiMorisawa 
以下のレビューの対応をお願いします。

2021-09-01 05:54 UTC, osaku-junichiro commented on .github/workflows/mention-to-slack.yml
> +          bot-name: "Send Mention from abeyuya/actions-mention-to-slack"
(cc @osaku-junichiro )
bot-name が長すぎるので `"Mention Bot"` に変更していただけますか？
（このレビューはレビューに対するメンションの挙動を確認も含みますが、レビュー指摘自体も対応を願いするものです。）

2021-09-01 06:15 UTC, KazukiMorisawa commented on .github/workflows/mention-to-slack.yml
> +          bot-name: "Send Mention from abeyuya/actions-mention-to-slack"
@osaku-junichiro (cc @KazukiMorisawa )
bot-name の変更を致しました。

2021-09-01 07:35 UTC, osaku-junichiro commented on .github/workflows/mention-to-slack.yml
> +          bot-name: "Send Mention from abeyuya/actions-mention-to-slack"
@KazukiMorisawa  (cc @osaku-junichiro  )
ご対応ありがとうございます。（テスト用のコメントを兼ねます。）

2021-09-02 03:00 UTC, KazukiMorisawa commented
@KazukiMorisawa GitHub が復旧したため再度テストです。

2021-09-02 04:49 UTC, osaku-junichiro commented on .github/workflows/mention-to-slack.yml
> +          bot-name: "Send Mention from abeyuya/actions-mention-to-slack"
@KazukiMorisawa (cc @osaku-junichiro ) テスト

2021-09-03 00:45 UTC, merged